[build]
  functions = "functions"
  publish = "public" 

[functions]
  directory = "functions"
  external_node_modules = ["ejs"]
  included_files = ["views/**", "quiz.json"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/quiz"
  status = 200