[build]
  functions = "functions"
  publish = "public"
  node_bundler = "esbuild"

[functions]
  directory = "functions"
  included_files = ["views/**", "quiz.json"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/quiz"
  status = 200
